### ISSUE TITLE
I think the upstream repo just vanished

### ISSUE THREAD

**Issue by Flash1232** [linuxserver/docker-pairdrop#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is no repository at https://github.com/schlagmichdoch/PairDrop (not even the user anymore)

### Expected Behavior

Well, that there IS a source repo.

### Steps To Reproduce

go to https://github.com/schlagmichdoch/PairDrop and see for yourself

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
-
```

### Container logs

```bash
-
```

**Comment by Roxedus** [comment]
We are aware, as our hourly checks has been failing. we have some other means of communication with this dev, and are hoping for some answers.

**Comment by DarkGhostHunter** [comment]
Same here. How it's going? Is there a Pairdrop fork around to fallback?

**Comment by dnet890** [comment]
true, But, the website still online and here is his response https://github.com/fm-sys/snapdrop-android/issues/356

**Comment by DarkGhostHunter** [comment]
It's no like it can be reverse engineered... at least not with the help of AI. The site must be just a build from GitHub actions hosted somewhere.

Edit: saw the response. Ducking GitHub. At least there are chances he will get his account back.

**Comment by stil-blue** [comment]
Hey @schlagmichdoch here.
As explained in the linked issue, it appears, that I am shadow banned by GitHub and I have yet to receive any answer to my reinstatement ticket.

Funnily enough, I still get notifications if anyone is @ me at my main account.

Sorry for the inconvenience! I have still no idea what the problem might be. Either it’s the repository name or my username, I could not come up with anything else that might in the faintest be against there guidelines.



> We are aware, as our hourly checks has been failing.

Has the situation created any other problem apart from the failing checks?

> The site must be just a build from GitHub actions hosted somewhere.

It’s hosted on a dedicated VPS.
The code can be found on the latest fork of the main repository here: https://github.com/babstar99/PairDrop/

**Comment by DarkGhostHunter** [comment]
Glad you're ok. 

In the meantime, i think it's safe to switch to the fork until GitHub reinstates the account.

**Comment by stil-blue** [comment]
Thanks!
I don't have any means to add a new release anyway so I'd suggest just leaving it as is until there are any news.

**Comment by kaindlnetwork** [comment]
> Hey @schlagmichdoch here. As explained in the linked issue, it appears, that I am shadow banned by GitHub and I have yet to receive any answer to my reinstatement ticket.
> 
> Funnily enough, I still get notifications if anyone is @ me at my main account.
> 
> Sorry for the inconvenience! I have still no idea what the problem might be. Either it’s the repository name or my username, I could not come up with anything else that might in the faintest be against there guidelines.
> 
> > We are aware, as our hourly checks has been failing.
> 
> Has the situation created any other problem apart from the failing checks?
> 
> > The site must be just a build from GitHub actions hosted somewhere.
> 
> It’s hosted on a dedicated VPS. The code can be found on the latest fork of the main repository here: https://github.com/babstar99/PairDrop/

Hello,

I would like to propose creating a fork or mirror of the project. My motivation stems from being a daily user and my inability to accept the lack of regular updates :D I am also willing to provide all the necessary computing resources to ensure its ongoing maintenance!

Best regards,

Fabian

https://github.com/kaindlnetwork/PairDrop

**Comment by stil-blue** [comment]
Hey @kaindlnetwork 

Above the reinstatement support ticket, they state it takes up to seven business days for them to reply due to high demand. If we count Mo-Fr the seventh day would be today. If they won't reply until the end of this week, I'll decide how to proceed.

Thanks for your interest though! I'm counting on your participation when everything is back to normal ;)

**Comment by schlagmichdoch** [comment]
Hey everyone, I'm the maintainer of the upstream repository.

Apparently, the flag as spam was lifted from my account and this account and my repositories are visible to the public again so this issue can be closed for now.

I will move to Codeberg in the near future though. See this issue for further information: https://github.com/schlagmichdoch/PairDrop/issues/284

I will notify the linuxserver dev team prior.

Thanks for your support!
