### ISSUE TITLE
[BUG] Pull Error v1.3.0 (rootless / file ownership?)

### ISSUE THREAD

**Issue by seth-hunter** [linuxserver/docker-pairdrop#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Docker:
$ docker pull lscr.io/linuxserver/pairdrop:latest
latest: Pulling from linuxserver/pairdrop
6f0fdad1ce92: Pull complete 
c61fe2056171: Pull complete 
604d992cfe46: Pull complete 
e4bccb8e029e: Pull complete 
2bf0bbf9b988: Extracting  31.44MB/31.44MB
aa59716395d4: Download complete 
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /app/pairdrop/node_modules/content-type/HISTORY.md: invalid argument

Podman:
$ podman pull lscr.io/linuxserver/pairdrop:latest
Trying to pull lscr.io/linuxserver/pairdrop:latest...
Getting image source signatures
Copying blob 6f0fdad1ce92 skipped: already exists  
Copying blob c61fe2056171 skipped: already exists  
Copying blob 604d992cfe46 skipped: already exists  
Copying blob e4bccb8e029e skipped: already exists  
Copying blob aa59716395d4 done  
Copying blob 2bf0bbf9b988 done  
Error: copying system image from manifest list: writing blob: adding layer with blob "sha256:2bf0bbf9b9887cc28b34d030769a562b466a34b6406bb664f9cf01496e6920da": processing tar file(potentially insufficient UIDs or GIDs available in user namespace (requested 1516583083:0 for /app/pairdrop/node_modules/content-type/HISTORY.md): Check /etc/subuid and /etc/subgid if configured locally and run podman-system-migrate: lchown /app/pairdrop/node_modules/content-type/HISTORY.md: invalid argument): exit status 1

### Steps To Reproduce

Rootless podman or docker installation:
podman/docker pull lscr.io/linuxserver/pairdrop:1.3.0

### Environment

```markdown
- OS: Multiple (Linux, x86-64 and arm64)
- How docker service was installed: rootless
```

### CPU architecture

x86-64

### Docker creation

```bash
n/a
```

### Container logs

```bash
n/a
```

**Comment by thespad** [comment]
We don't currently support rootless for our images, however, this may be of help to you https://github.com/moby/moby/issues/43576

**Comment by seth-hunter** [comment]
@thespad: shame, most other linuxserver images i've used work fine rootless.  UID of 1516583083, thus needing to increase subuid limit per user to over 1.5 billion, seems... unintended.

**Comment by thespad** [comment]
It is unintended, but we don't test for rootless, so any number of things can happen that might interact weirdly with it.

**Comment by seth-hunter** [comment]
Understood; request you please consider PR #5 to resolve this.

**Comment by thespad** [comment]
Please can you try `lspipepr/pairdrop:v1.4.1-pkg-6187fbf7-pr-7` and see if it resolves your issue

**Comment by seth-hunter** [comment]
@thespad, yes, that fixes the problem for me as well.  Thank you.
