### ISSUE TITLE
[BUG] Unable to see other devices in Pairdrop interface

### ISSUE THREAD

**Issue by schumi2004** [linuxserver/docker-pairdrop#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i go to my pairdrop interface (https://pairdrop.mydomain.com) i don't see any other devices.
When checking the logs i noticed the following error:

npm WARN logfile Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm WARN logfile  error cleaning log files [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
npm WARN logfile   errno: -13,
npm WARN logfile   code: 'EACCES',
npm WARN logfile   syscall: 'scandir',
npm WARN logfile   path: '/root/.npm/_logs'
npm WARN logfile }

This suggest it's looking for logs releated to NGINX Proxy Manager?
I did use NPM before but i was giving me to many issues so reverted back to SWAG.

Not using pairdrop on a daily basis so can't tell if it is related to NPM or not, als browsing to the internal IP doesn't show me any other clients conencted to Pairdrop.

### Expected Behavior

A working environment.

### Steps To Reproduce

Just install latest using docker-compose and check logs.

note: Previously i was running a developer build which was giving me the same result.

### Environment

```markdown
Using Docker LXC in Proxmox and installed container using docker-compose
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "2.1"
services:
  pairdrop:
    image: lscr.io/linuxserver/pairdrop:latest
    container_name: pairdrop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      ipvlan_custom:
        ipv4_address: 10.0.0.179

networks:
  ipvlan_custom:
    name: ipvlan_custom
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║      
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support the app dev(s) visit:
PairDrop: https://www.buymeacoffee.com/pairdrop
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
[custom-init] No custom files found, skipping...
npm WARN logfile Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm WARN logfile  error cleaning log files [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
npm WARN logfile   errno: -13,
npm WARN logfile   code: 'EACCES',
npm WARN logfile   syscall: 'scandir',
npm WARN logfile   path: '/root/.npm/_logs'
npm WARN logfile }
> pairdrop@1.5.0 start
> node index.js  
PairDrop is running on port 3000
[ls.io-init] done.
```

**Comment by thespad** [comment]
I don't think the warning will be causing your issues, but it looks like an upstream change is triggering them. I'll get that fixed.

**Comment by thespad** [comment]
The warning has been fixed by the latest build.

**Comment by schumi2004** [comment]
@thespad you were right. Turns out that 1 of my mobile apps was setting up a tunnel to different location and therefore wasn't been seen on the interface.

Sorry for the inconvenience
